### ISSUE TITLE
Is sympy broken or am I doing something stupid?

### ISSUE THREAD

**Issue by kylerchin** [DXsmiley/mathbot#81]
On running `python3.6 entrypoint.py`, I get this message:
```
Main process starting up
Could not find gateway queue to connect to
Running shards [0] (total 1)
/usr/local/lib/python3.6/dist-packages/discord/client.py:250: DeprecationWarning: fetch_offline_members is deprecated, use chunk_guilds_at_startup instead
  self._connection = self._get_state(**options)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/bot.py", line 607, in _load_from_module_spec
    spec.loader.exec_module(lib)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/disrupt/discordbots/mathbot/mathbot/modules/calcmod.py", line 10, in <module>
    import calculator
  File "/home/disrupt/discordbots/mathbot/mathbot/calculator/__init__.py", line 11, in <module>
    import calculator.interpereter
  File "/home/disrupt/discordbots/mathbot/mathbot/calculator/interpereter.py", line 14, in <module>
    import calculator.runtime as runtime
  File "/home/disrupt/discordbots/mathbot/mathbot/calculator/runtime.py", line 13, in <module>
    from calculator.bytecode import *
  File "/home/disrupt/discordbots/mathbot/mathbot/calculator/bytecode.py", line 3, in <module>
    import calculator.errors
  File "/home/disrupt/discordbots/mathbot/mathbot/calculator/errors.py", line 2, in <module>
    import calculator.formatter
  File "/home/disrupt/discordbots/mathbot/mathbot/calculator/formatter.py", line 14, in <module>
    ALL_SYMPY_CLASSES = tuple(sympy.core.all_classes) # pylint: disable=no-member
AttributeError: module 'sympy.core' has no attribute 'all_classes'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "entrypoint.py", line 49, in <module>
    bot.run(retrieve_parameters())
  File "/home/disrupt/discordbots/mathbot/mathbot/bot.py", line 271, in run
    MathBot(parameters).run()
  File "/home/disrupt/discordbots/mathbot/mathbot/bot.py", line 72, in __init__
    self.load_extension(i)
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/bot.py", line 664, in load_extension
    self._load_from_module_spec(spec, name)
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/bot.py", line 610, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'modules.calcmod' raised an error: AttributeError: module 'sympy.core' has no attribute 'all_classes'
```
I think I'm stupid idk what's going on, I can't figure out any way to fix this

**Comment by DXsmiley** [comment]
MathBot requires sympy 1.4 and not any older _or newer_ version. Check that you have that version installed.
