### ISSUE TITLE
AttributeError when trying to run the calculator against a file

### ISSUE THREAD

**Issue by iomintz** [DXsmiley/mathbot#86]
```py
➤ python -m calculator tmp/script.c5
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/code/vcs/git/com/github/@/DXsmiley/mathbot/mathbot/calculator/__main__.py", line 79, in <module>
    main()
  File "/home/user/code/vcs/git/com/github/@/DXsmiley/mathbot/mathbot/calculator/__main__.py", line 27, in main
    btc = prepare_runtime(bytecode.CodeBuilder(), ast, exportable = args.compile)
AttributeError: module 'calculator.bytecode' has no attribute 'CodeBuilder'
```

I'm on commit a6b8feae38d4c29903872e63f77b285bc8af2685. I tried with the --compile / --trace flags, and got the same error.

**Comment by DXsmiley** [comment]
I think I fixed this. Can you grab the latest release and see if it works for you?

**Comment by iomintz** [comment]
Confirmed working
